# Generated by Django 3.0.6 on 2021-02-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('omschrijving', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Actief', 'Actief'), ('Inactief', 'Inactief')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Projecttaken',
            },
        ),
    ]
