# Generated by Django 3.0.6 on 2021-03-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claus_administratie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KostenCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=20)),
                ('omschrijving', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Actief', 'Actief'), ('Inactief', 'Inactief')], max_length=200)),
                ('bedrijfsadministratie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claus_administratie.BedrijfsAdministratie')),
            ],
            options={
                'verbose_name_plural': 'Kostencodes',
            },
        ),
    ]
