# Generated by Django 3.0.6 on 2021-02-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claus_administratie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnummer', models.CharField(blank=True, max_length=200)),
                ('projectomschrijving', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Actief', 'Actief'), ('Inactief', 'Inactief'), ('Afgesloten', 'Afgesloten')], max_length=200)),
                ('bedrijfsadministratie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claus_administratie.BedrijfsAdministratie')),
                ('projectleider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projecten',
            },
        ),
    ]
