# Generated by Django 3.0.6 on 2021-01-30 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persoonnr', models.CharField(max_length=30)),
                ('naam', models.CharField(max_length=100)),
                ('in_dienst_status', models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee')], max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personen',
            },
        ),
    ]
