# Generated by Django 3.0.6 on 2021-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claus_personen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personen',
            name='is_administratie',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
