# Generated by Django 3.0.6 on 2021-02-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claus_administratie', '0001_initial'),
        ('claus_personen', '0002_personen_is_administratie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personen',
            name='is_administratie',
        ),
        migrations.AddField(
            model_name='personen',
            name='administratie_werkgever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='claus_administratie.BedrijfsAdministratie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personen',
            name='gebruikersgroep',
            field=models.CharField(choices=[('Administratie', 'Administratie'), ('Vestigingleider', 'Vestigingleider'), ('Teamleider', 'Teamleider'), ('Uitvoerend', 'Uitvoerend')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
