# Generated by Django 3.0.6 on 2021-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claus_personen', '0003_auto_20210204_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='personen',
            name='persoon_guid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
