# Generated by Django 3.0.6 on 2021-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claus_personen', '0004_personen_persoon_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personen',
            name='gebruikersgroep',
        ),
    ]
