# Generated by Django 3.0.6 on 2021-04-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('claus_personen', '0005_remove_personen_gebruikersgroep'),
    ]

    operations = [
        migrations.AddField(
            model_name='personen',
            name='gebruikersgroep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
