# Generated by Django 3.0.6 on 2021-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedrijfsAdministratie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnummer', models.CharField(max_length=10)),
                ('bedrijfsnaam', models.CharField(max_length=200)),
                ('kvk_nummer', models.CharField(max_length=200)),
                ('vestigings_nummer', models.CharField(max_length=200)),
                ('straatnaam_nummer', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('plaats', models.CharField(max_length=200)),
                ('omschrijving', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Actief', 'Actief'), ('Inactief', 'Inactief')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Bedrijven',
            },
        ),
    ]
